### ISSUE TITLE
NPM private registry key?

### ISSUE THREAD

**Issue by shaun-sweet** [credativ/plutono#49]
I'm seeing when trying to build this, that i'm getting 401 errors when npm is attempting to install the deps.  this happens in docker as well and manually trying to install.  Is there some process to get on the private repo or any alternatives?

**Comment by broox** [comment]
+1

How can we get access to the following packages?

- [plutono-data](https://github.com/orgs/credativ/packages/npm/package/plutono-data)
- [plutono-e2e](https://github.com/orgs/credativ/packages/npm/package/plutono-e2e)
- [plutono-e2e-selectors](https://github.com/orgs/credativ/packages/npm/package/plutono-e2e-selectors)
- [plutono-ui](https://github.com/orgs/credativ/packages/npm/package/plutono-ui)
- [plutono-toolkit](https://github.com/orgs/credativ/packages/npm/package/plutono-toolkit)
- [plutono-runtime](https://github.com/orgs/credativ/packages/npm/package/plutono-runtime)

Manually building the packages in [/packages](https://github.com/credativ/plutono/tree/main/packages) is tricky since `plutono-toolkit` [requires plutono-toolkit in order to build](https://github.com/credativ/plutono/blob/main/packages/plutono-toolkit/package.json#L22).

**Comment by credativ-dar** [comment]
You can see the package but not download it, correct? The package is set to public, what I currently don't see is why it can be only seen but not be downloaded by the "public".

**Comment by credativ-dar** [comment]
Are you able to download any other packages from Github? I think it is in general not possible to download packages without a personal access token (PAT) set up, so this is not specific to this repository or these packages.
Try creating a "classic" [PAT](https://github.com/settings/tokens) with `read:packages` access and create a `.npmrc` file in your home directory with the following contents:

```
//npm.pkg.github.com/:_authToken=<your token>
@credativ:registry=https://npm.pkg.github.com/
```

Let me know if that helps, those packages should be public and available to anyone, the source code is here anyway :wink:

**Comment by broox** [comment]
aha! Thanks, @credativ-dar.

I've not installed packages from github registries before, so I totally missed those important details. Would you welcome a PR to update the `README` with installation instructions?

I was able to get half of the packages manually built with the source code included in `plutono/packages`, but i had to create my own `plutono-toolkit-init` script to get `plutono-toolkit` built/installed, and also modify many of the `package.json` files, which seemed to be missing some dependencies (mostly `@types/*`, `rimraf`, etc).

Adding the personal access token allowed most of the packages to be installed from github, but it failed on `plutono-aws-sdk`

```
➤ YN0035: │ @credativ/plutono-aws-sdk@npm:0.0.4: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@credativ%2fplutono-aws-sdk
```

**Comment by credativ-dar** [comment]
Sorry for the late replay and thanks for the PR! We just merged https://github.com/credativ/plutono/pull/50 with your instructions and therefore I think this issue is resolved. Thanks again for bringing it up.
